#!/usr/bin/env bash
# tunnel.sh [start|stop|status] — publish the local board on a public ngrok URL,
# behind a Google login restricted to a personal allow-list.
#
# WHY THE AUTH GATE IS NOT OPTIONAL: the FastAPI app ships no authentication of
# its own, and `POST /api/windows/<pid>/keys` types arbitrary keystrokes into a
# tmux pane. A tunnel without a traffic policy is therefore a public shell on
# this host, on a fixed hostname that gets scanned. This script generates the
# policy itself and refuses to start without one, so "expose the board" and
# "put a login in front of it" cannot come apart.
#
# The gate is two ngrok traffic-policy rules, and it takes BOTH: the first
# forces a Google sign-in, the second 403s every authenticated identity that
# is not on the allow-list — otherwise any Google account on earth would do.
#
# Config lives in .env.local (gitignored — a domain and a personal address are
# nobody else's business, and this file is public):
#   FLEET_TUNNEL_DOMAIN          reserved ngrok domain, e.g. foo.ngrok-free.dev
#   FLEET_TUNNEL_ALLOWED_EMAILS  comma-separated Google addresses allowed in
#   CLAUDE_FLEET_PORT            local board port (default 7879, as in run.sh)
# The ngrok authtoken is not read here at all: `ngrok config add-authtoken`
# keeps it in ~/.config/ngrok/ngrok.yml, outside the repo.
#
# Exit codes: 0 ok · 2 usage/config · 3 board not running · 4 tunnel failed.
set -uo pipefail
cd "$(dirname "$0")/.."

if [ -f .env.local ]; then
    set -a; source .env.local; set +a
fi

PORT="${CLAUDE_FLEET_PORT:-7879}"
DOMAIN="${FLEET_TUNNEL_DOMAIN:-}"
EMAILS="${FLEET_TUNNEL_ALLOWED_EMAILS:-}"
NGROK_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/ngrok"
# Generated, never committed: it is derived from .env.local on every start, so
# editing the allow-list there and restarting is the whole update procedure.
POLICY="$NGROK_DIR/policy.generated.yml"
LOG="$NGROK_DIR/tunnel.log"

case "${1:-start}" in
stop)
    # -x matches the process NAME exactly. A -f pattern would also match this
    # script's own command line (and any shell that has "ngrok" in its args),
    # which is a fast way to kill the caller instead of the tunnel.
    if pkill -x ngrok 2>/dev/null; then echo "[tunnel] stopped"; else echo "[tunnel] nothing running"; fi
    exit 0
    ;;
status)
    if ! pgrep -x ngrok >/dev/null; then echo "[tunnel] not running"; exit 0; fi
    echo "[tunnel] running${DOMAIN:+ -> https://$DOMAIN}"
    [ -n "$DOMAIN" ] && curl -sS -o /dev/null --max-time 15 \
        -w "[tunnel] anonymous request gets HTTP %{http_code} (302 = redirected to the login, gate is up)\n" \
        "https://$DOMAIN/"
    exit 0
    ;;
start) ;;
*)
    echo "usage: scripts/tunnel.sh [start|stop|status]" >&2
    exit 2
    ;;
esac

# --- config checks ----------------------------------------------------------
if [ -z "$DOMAIN" ] || [ -z "$EMAILS" ]; then
    echo "error: set FLEET_TUNNEL_DOMAIN and FLEET_TUNNEL_ALLOWED_EMAILS in .env.local" >&2
    echo "       (reserve a free domain at https://dashboard.ngrok.com/domains)" >&2
    exit 2
fi
command -v ngrok >/dev/null 2>&1 || {
    echo "error: ngrok not on PATH — https://ngrok.com/download, then: ngrok config add-authtoken <token>" >&2
    exit 2
}

# The board binds loopback only. Starting a tunnel to a dead port would publish
# ngrok's own error page rather than anything useful, so check first.
if ! curl -s -o /dev/null --max-time 5 "http://127.0.0.1:$PORT/"; then
    echo "error: nothing serving on 127.0.0.1:$PORT — start the board first (./run.sh)" >&2
    exit 3
fi

# --- build the traffic policy ----------------------------------------------
# Each address is interpolated into a CEL expression, so anything that could
# terminate the quoting is rejected rather than escaped.
DENY=""
IFS=',' read -ra ADDRS <<< "$EMAILS"
for addr in "${ADDRS[@]}"; do
    addr="$(printf '%s' "$addr" | tr -d '[:space:]')"
    [ -n "$addr" ] || continue
    if ! [[ "$addr" =~ ^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$ ]]; then
        echo "error: not a usable email address in FLEET_TUNNEL_ALLOWED_EMAILS: $addr" >&2
        exit 2
    fi
    # Rule fires (= denies) only when the identity matches NO allowed address,
    # hence != joined by &&.
    DENY="${DENY:+$DENY && }actions.ngrok.oauth.identity.email != '$addr'"
done
[ -n "$DENY" ] || { echo "error: FLEET_TUNNEL_ALLOWED_EMAILS has no addresses" >&2; exit 2; }

mkdir -p "$NGROK_DIR"
umask 077
cat > "$POLICY" <<EOF
# GENERATED by scripts/tunnel.sh from .env.local — edits here are overwritten.
on_http_request:
  - actions:
      - type: oauth
        config:
          provider: google
  - expressions:
      - "$DENY"
    actions:
      - type: deny
        config:
          status_code: 403
EOF

# --- start ------------------------------------------------------------------
# The policy is passed with --traffic-policy-file rather than declared as an
# `endpoints:` entry in ngrok.yml: as of ngrok 3.39 the agent config rejects
# every spelling of an inline traffic_policy (a nested mapping is flattened to
# "invalid value of type 'map' for traffic policy rule array"; a block string
# comes back as "type 'str'"). An endpoint entry that silently dropped the
# policy would publish the board wide open, so the CLI flag is the only form
# used here.
#
# A free ngrok plan allows one agent session, so a stale agent would just fight
# this one for the domain.
pkill -x ngrok 2>/dev/null && sleep 1

setsid ngrok http "$PORT" \
    --url "https://$DOMAIN" \
    --traffic-policy-file "$POLICY" \
    --log stdout --log-format logfmt \
    > "$LOG" 2>&1 < /dev/null &

for _ in $(seq 20); do
    grep -q "started tunnel" "$LOG" 2>/dev/null && break
    sleep 1
done

if grep -q "started tunnel" "$LOG" 2>/dev/null; then
    echo "[tunnel] up -> https://$DOMAIN (Google sign-in required)"
    exit 0
fi
echo "[tunnel] failed to start; last lines of $LOG:" >&2
tail -5 "$LOG" >&2
exit 4
